version: '3'
services:
  psql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - '5437:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'

volumes:
  postgres-data: